[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.5"
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.12", features = ["csr", "nightly"] }
leptos_router = { version = "0.6.14", features = ["csr", "nightly"] }


